export const MODULES = [
  {
    id: 'ghost',
    name: 'Ghost Region Resolver',
    icon: '👻',
    description: 'Derive areas of missing/censored regions from adjacency constraints and global area closure.',
    path: '/dashboard/ghost',
  },
  {
    id: 'geometer',
    name: 'Intrinsic Geometer',
    icon: '📐',
    description: 'Reconstruct 2D Riemannian manifold from edge lengths and face area constraints via SMACOF.',
    path: '/dashboard/geometer',
  },
  {
    id: 'positioning',
    name: 'Absolute Positioning',
    icon: '📍',
    description: 'Determine absolute positions using raw distance measurements between ground stations.',
    path: '/dashboard/positioning',
  },
  {
    id: 'celestial',
    name: 'Celestial Dynamics',
    icon: '🪐',
    description: 'Compute geodesics and simulate particle motion under arbitrary force fields.',
    path: '/dashboard/celestial',
  },
  {
    id: 'extraterrestrial',
    name: 'Extraterrestrial Mapper',
    icon: '🌍',
    description: 'Reconstruct intrinsic shape of celestial bodies from raw range measurements.',
    path: '/dashboard/extraterrestrial',
  },
  {
    id: 'distortion',
    name: 'Distortion Observatory',
    icon: '🔍',
    description: 'Compare absolute maps against projections and quantify distortion via strain tensors.',
    path: '/dashboard/distortion',
  },
  {
    id: 'environmental',
    name: 'Environmental Dynamics',
    icon: '🌊',
    description: 'Simulate sea-level rise and volumetric changes on absolute coastlines.',
    path: '/dashboard/environmental',
  },
  {
    id: 'stellar',
    name: 'Stellar Positioning',
    icon: '⭐',
    description: 'Navigate deep-space probes using VLBI angular separations between quasars.',
    path: '/dashboard/stellar',
  },
  {
    id: 'anomaly',
    name: 'Anomaly Detector',
    icon: '⚠️',
    description: 'Monitor edge-length drifts and flag significant changes beyond rigid rotation.',
    path: '/dashboard/anomaly',
  },
];
