export const MODULES = [
  {
    id: 'simulator',
    name: 'Simulator',
    icon: '🧪',
    description: 'Visual execution of all six simulation scenarios with live Chart.js charts.',
    path: '/dashboard/simulator',
    apiEndpoint: '/dynamics/simulate',
    testPayload: {
      start: [0, 0, 0],
      initial_velocity: [1, 0, 0],
      force_law: 'inertial',
      dt: 0.01,
      t_max: 10,
    },
  },
  {
    id: 'ghost-resolver',
    name: 'Ghost Resolver',
    icon: '🔮',
    description: 'Derive unknown areas from topological residual closure and global area constraints.',
    path: '/dashboard/ghost-resolver',
    apiEndpoint: '/ghost/resolve',
    testPayload: {
      polygons: [
        { name: 'World', area: 510000000000000 },
        { name: 'Known', area: 400000000000000 },
        { name: 'Unknown', area: null, claimed_area: 50000000000000, neighbours: ['World'] },
      ],
      global_enclosure: 'World',
      global_area: 510000000000000,
    },
  },
  {
    id: 'distortion-observatory',
    name: 'Distortion Observatory',
    icon: '📊',
    description: 'Interactive manifold visualization with strain tensor heatmap and deviation ranking.',
    path: '/dashboard/distortion-observatory',
    apiEndpoint: '/projections/scores',
    testPayload: null,
  },
  {
    id: 'consensus-hall',
    name: 'Consensus Hall',
    icon: '🏛️',
    description: 'Colonial Distortion Scores for scholarly map projections.',
    path: '/dashboard/consensus-hall',
    apiEndpoint: '/projections/scores',
    testPayload: null,
  },
  {
    id: 'terraformer',
    name: 'Terraformer',
    icon: '🌊',
    description: 'Simulate sea-level rise and compute coastline changes for every nation.',
    path: '/dashboard/terraformer',
    apiEndpoint: '/terraformation',
    testPayload: { sea_level_rise_m: 10 },
  },
  {
    id: 'anomaly-detector',
    name: 'Anomaly Detector',
    icon: '⚡',
    description: 'Detect edge-length drifts exceeding 1cm/day with Z-score analysis.',
    path: '/dashboard/anomaly-detector',
    apiEndpoint: '/anomaly/latest',
    testPayload: null,
  },
  {
    id: 'physical-truth',
    name: 'Physical Truth',
    icon: '🌍',
    description: 'Reconstruct the Physical Truth manifold from real DEM-derived edge lengths.',
    path: '/dashboard/physical-truth',
    apiEndpoint: '/solve/physical-truth',
    testPayload: null,
  },
  {
    id: 'alien-reconstruct',
    name: 'Alien Geometer',
    icon: '👽',
    description: 'Reconstruct intrinsic shape from raw edge lengths — Flat / Ellipsoidal / Potato.',
    path: '/dashboard/alien-reconstruct',
    apiEndpoint: '/alien/reconstruct',
    testPayload: {
      edges: [
        { source: 'A', target: 'B', length: 1.0, source_type: 'topology' },
        { source: 'B', target: 'C', length: 1.0, source_type: 'topology' },
        { source: 'C', target: 'A', length: 1.0, source_type: 'topology' },
      ],
    },
  },
  {
    id: 'dynamics',
    name: 'Celestial Dynamics',
    icon: '🪐',
    description: 'Simulate particle motion under user-defined force fields — no targeting outputs.',
    path: '/dashboard/dynamics',
    apiEndpoint: '/dynamics/simulate',
    testPayload: {
      start: [0, 0, 0],
      initial_velocity: [1, 0, 0],
      force_law: 'inertial',
      mu: 1.0,
      dt: 0.01,
      t_max: 10,
    },
  },
  {
    id: 'terraformation',
    name: 'Terraformation',
    icon: '🌿',
    description: 'Simulate terraforming scenarios with volumetric transfers.',
    path: '/dashboard/terraformation',
    apiEndpoint: '/terraformation',
    testPayload: { sea_level_rise_m: 5 },
  },
];
